#4 TO - DO - Task
Please complete all the problem listed below.
4.1 Exercise on Functions:
Task - 1:
Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.
• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.
• Conversion Options:
1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L).

In [1]:
# Task 1: Unit Converter
def convert_length(value, from_unit, to_unit):
    """
    Converts length between meters and feet.

    Parameters:
        value (float): The value to convert
        from_unit (str): The unit to convert from ('m' or 'ft')
        to_unit (str): The unit to convert to ('m' or 'ft')

    Returns:
        float: The converted value
    """
    if from_unit == 'm' and to_unit == 'ft':
        return value * 3.28084
    elif from_unit == 'ft' and to_unit == 'm':
        return value / 3.28084
    else:
        raise ValueError("Invalid length units. Use 'm' or 'ft'.")

def convert_weight(value, from_unit, to_unit):
    """
    Converts weight between kilograms and pounds.

    Parameters:
        value (float): The value to convert
        from_unit (str): The unit to convert from ('kg' or 'lbs')
        to_unit (str): The unit to convert to ('kg' or 'lbs')

    Returns:
        float: The converted value
    """
    if from_unit == 'kg' and to_unit == 'lbs':
        return value * 2.20462
    elif from_unit == 'lbs' and to_unit == 'kg':
        return value / 2.20462
    else:
        raise ValueError("Invalid weight units. Use 'kg' or 'lbs'.")

def convert_volume(value, from_unit, to_unit):
    """
    Converts volume between liters and gallons.

    Parameters:
        value (float): The value to convert
        from_unit (str): The unit to convert from ('L' or 'gal')
        to_unit (str): The unit to convert to ('L' or 'gal')

    Returns:
        float: The converted value
    """
    if from_unit == 'L' and to_unit == 'gal':
        return value * 0.264172
    elif from_unit == 'gal' and to_unit == 'L':
        return value / 0.264172
    else:
        raise ValueError("Invalid volume units. Use 'L' or 'gal'.")

def unit_converter():
    """
    Main function to handle user interaction for unit conversion.
    """
    print("Unit Converter Program")
    print("1. Length (meters <-> feet)")
    print("2. Weight (kilograms <-> pounds)")
    print("3. Volume (liters <-> gallons)")

    try:
        choice = input("Enter your choice (1-3): ")

        if choice == '1':
            print("\nLength Conversion:")
            print("a. Meters to Feet")
            print("b. Feet to Meters")
            sub_choice = input("Enter choice (a/b): ").lower()
            value = float(input("Enter value: "))

            if sub_choice == 'a':
                result = convert_length(value, 'm', 'ft')
                print(f"{value} meters = {result:.4f} feet")
            elif sub_choice == 'b':
                result = convert_length(value, 'ft', 'm')
                print(f"{value} feet = {result:.4f} meters")
            else:
                print("Invalid choice")

        elif choice == '2':
            print("\nWeight Conversion:")
            print("a. Kilograms to Pounds")
            print("b. Pounds to Kilograms")
            sub_choice = input("Enter choice (a/b): ").lower()
            value = float(input("Enter value: "))

            if sub_choice == 'a':
                result = convert_weight(value, 'kg', 'lbs')
                print(f"{value} kg = {result:.4f} lbs")
            elif sub_choice == 'b':
                result = convert_weight(value, 'lbs', 'kg')
                print(f"{value} lbs = {result:.4f} kg")
            else:
                print("Invalid choice")

        elif choice == '3':
            print("\nVolume Conversion:")
            print("a. Liters to Gallons")
            print("b. Gallons to Liters")
            sub_choice = input("Enter choice (a/b): ").lower()
            value = float(input("Enter value: "))

            if sub_choice == 'a':
                result = convert_volume(value, 'L', 'gal')
                print(f"{value} L = {result:.4f} gallons")
            elif sub_choice == 'b':
                result = convert_volume(value, 'gal', 'L')
                print(f"{value} gallons = {result:.4f} L")
            else:
                print("Invalid choice")
        else:
            print("Invalid choice. Please enter 1, 2, or 3.")

    except ValueError as e:
        print(f"Error: {e}")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

unit_converter()

Unit Converter Program
1. Length (meters <-> feet)
2. Weight (kilograms <-> pounds)
3. Volume (liters <-> gallons)
Enter your choice (1-3): ]2
Invalid choice. Please enter 1, 2, or 3.


Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.
• Requirements:

1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [2]:
# Task 2: Mathematical Operations on List

def calculate_sum(numbers):
    """
    Calculates the sum of a list of numbers.

    Parameters:
        numbers (list): List of numbers

    Returns:
        float: Sum of the numbers
    """
    return sum(numbers)

def calculate_average(numbers):
    """
    Calculates the average of a list of numbers.

    Parameters:
        numbers (list): List of numbers

    Returns:
        float: Average of the numbers
    """
    if len(numbers) == 0:
        raise ValueError("Cannot calculate average of empty list")
    return sum(numbers) / len(numbers)

def find_maximum(numbers):
    """
    Finds the maximum value in a list.

    Parameters:
        numbers (list): List of numbers

    Returns:
        float: Maximum value
    """
    if len(numbers) == 0:
        raise ValueError("Cannot find maximum of empty list")
    return max(numbers)

def find_minimum(numbers):
    """
    Finds the minimum value in a list.

    Parameters:
        numbers (list): List of numbers

    Returns:
        float: Minimum value
    """
    if len(numbers) == 0:
        raise ValueError("Cannot find minimum of empty list")
    return min(numbers)

def math_operations():
    """
    Main function to handle mathematical operations on a list of numbers.
    """
    print("Mathematical Operations on List")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    try:
        choice = input("Enter your choice (1-4): ")

        # Get input and convert to list of numbers
        input_str = input("Enter numbers separated by spaces: ")
        if not input_str.strip():
            raise ValueError("Empty input provided")

        numbers = [float(x) for x in input_str.split()]

        if len(numbers) == 0:
            raise ValueError("No numbers provided")

        if choice == '1':
            result = calculate_sum(numbers)
            print(f"Sum: {result}")
        elif choice == '2':
            result = calculate_average(numbers)
            print(f"Average: {result}")
        elif choice == '3':
            result = find_maximum(numbers)
            print(f"Maximum: {result}")
        elif choice == '4':
            result = find_minimum(numbers)
            print(f"Minimum: {result}")
        else:
            print("Invalid choice")

    except ValueError as e:
        print(f"Error: {e}")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

math_operations()

Mathematical Operations on List
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice (1-4): 3
Enter numbers separated by spaces: 9
Maximum: 9.0


4.2 Exercise on List Manipulation:
1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.
• Requirements:
– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].
2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.
• Requirements:
– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).
– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.
• Requirements:
– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.
• Requirements:
– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].
5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.
• Requirements:
– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.
– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].
6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.
• Requirements:
– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.
– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].
7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.
• Requirements:
– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [3]:
# 1. Extract Every Other Element
def extract_every_other(lst):
    """
    Extracts every other element from a list, starting from the first element.

    Parameters:
        lst (list): Input list

    Returns:
        list: Every other element starting from index 0
    """
    return lst[::2]


print("1. Extract Every Other Element:")
print(extract_every_other([1, 2, 3, 4, 5, 6]))  # Output: [1, 3, 5]


# 2. Slice a Sublist
def get_sublist(lst, start, end):
    """
    Returns a sublist from start to end (inclusive).

    Parameters:
        lst (list): Input list
        start (int): Starting index
        end (int): Ending index

    Returns:
        list: Sublist from start to end (inclusive)
    """
    return lst[start:end+1]


print("\n2. Slice a Sublist:")
print(get_sublist([1, 2, 3, 4, 5, 6], 2, 4))  # Output: [3, 4, 5]


# 3. Reverse a List Using Slicing
def reverse_list(lst):
    """
    Reverses a list using slicing.

    Parameters:
        lst (list): Input list

    Returns:
        list: Reversed list
    """
    return lst[::-1]

# Test
print("\n3. Reverse a List:")
print(reverse_list([1, 2, 3, 4, 5]))  # Output: [5, 4, 3, 2, 1]


# 4. Remove the First and Last Elements
def remove_first_last(lst):
    """
    Removes the first and last elements of a list.

    Parameters:
        lst (list): Input list

    Returns:
        list: List without first and last elements
    """
    return lst[1:-1]

print("\n4. Remove First and Last:")
print(remove_first_last([1, 2, 3, 4, 5]))  # Output: [2, 3, 4]


# 5. Get the First n Elements
def get_first_n(lst, n):
    """
    Extracts the first n elements from a list.

    Parameters:
        lst (list): Input list
        n (int): Number of elements to extract

    Returns:
        list: First n elements
    """
    return lst[:n]

print("\n5. Get First n Elements:")
print(get_first_n([1, 2, 3, 4, 5], 3))  # Output: [1, 2, 3]


# 6. Extract Elements from the End
def get_last_n(lst, n):
    """
    Extracts the last n elements of a list.

    Parameters:
        lst (list): Input list
        n (int): Number of elements from the end

    Returns:
        list: Last n elements
    """
    return lst[-n:]

print("\n6. Get Last n Elements:")
print(get_last_n([1, 2, 3, 4, 5], 2))  # Output: [4, 5]


# 7. Extract Elements in Reverse Order
def reverse_skip(lst):
    """
    Extracts every second element starting from the second-to-last, moving backward.

    Parameters:
        lst (list): Input list

    Returns:
        list: Elements in reverse order with skip
    """
    return lst[-2::-2]

print("\n7. Reverse Skip:")
print(reverse_skip([1, 2, 3, 4, 5, 6]))  # Output: [5, 3, 1]

1. Extract Every Other Element:
[1, 3, 5]

2. Slice a Sublist:
[3, 4, 5]

3. Reverse a List:
[5, 4, 3, 2, 1]

4. Remove First and Last:
[2, 3, 4]

5. Get First n Elements:
[1, 2, 3]

6. Get Last n Elements:
[4, 5]

7. Reverse Skip:
[5, 3, 1]


4.3 Exercise on Nested List:
1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.
• Requirements:
– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.
– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].
2. Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices.
• Requirements:
– Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.
– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.
3. Sum of All Elements in a Nested List:
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).
• Requirements:
– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.
4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list.
• Requirements:
– Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.
– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].

5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth).
• Requirements:
– Define a function find max(lst) that takes a nested list lst and returns the maximum
element.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.
• Requirements:
– Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.
– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.

7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.
• Requirements:
– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.
– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

8. Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.
• Requirements:
– Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.
– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [4]:
# 4.3 Exercise on Nested List

# 1. Flatten a Nested List
def flatten(lst):
    """
    Flattens a nested list into a single list.

    Parameters:
        lst (list): Nested list

    Returns:
        list: Flattened list
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(flatten(item))
        else:
            result.append(item)
    return result

# Test
print("1. Flatten Nested List:")
print(flatten([[1, 2], [3, 4], [5]]))  # Output: [1, 2, 3, 4, 5]


# 2. Accessing Nested List Elements
def access_nested_element(lst, indices):
    """
    Extracts a specific element from a nested list given its indices.

    Parameters:
        lst (list): Nested list
        indices (list): List of indices

    Returns:
        The element at the specified position
    """
    current = lst
    for index in indices:
        current = current[index]
    return current

# Test
print("\n2. Access Nested Element:")
lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(access_nested_element(lst, [1, 2]))  # Output: 6


# 3. Sum of All Elements in a Nested List
def sum_nested(lst):
    """
    Calculates the sum of all numbers in a nested list.

    Parameters:
        lst (list): Nested list

    Returns:
        float: Sum of all elements
    """
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

# Test
print("\n3. Sum Nested List:")
print(sum_nested([[1, 2], [3, [4, 5]], 6]))  # Output: 21


# 4. Remove Specific Element from a Nested List
def remove_element(lst, elem):
    """
    Removes all occurrences of a specific element from a nested list.

    Parameters:
        lst (list): Nested list
        elem: Element to remove

    Returns:
        list: Modified list with element removed
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            new_sublist = remove_element(item, elem)
            if new_sublist:  # Only add non-empty lists
                result.append(new_sublist)
        elif item != elem:
            result.append(item)
    return result

# Test
print("\n4. Remove Element:")
print(remove_element([[1, 2], [3, 2], [4, 5]], 2))  # Output: [[1], [3], [4, 5]]


# 5. Find the Maximum Element in a Nested List
def find_max(lst):
    """
    Finds the maximum element in a nested list.

    Parameters:
        lst (list): Nested list

    Returns:
        The maximum element
    """
    max_val = float('-inf')
    for item in lst:
        if isinstance(item, list):
            max_val = max(max_val, find_max(item))
        else:
            max_val = max(max_val, item)
    return max_val

# Test
print("\n5. Find Maximum:")
print(find_max([[1, 2], [3, [4, 5]], 6]))  # Output: 6


# 6. Count Occurrences of an Element in a Nested List
def count_occurrences(lst, elem):
    """
    Counts how many times a specific element appears in a nested list.

    Parameters:
        lst (list): Nested list
        elem: Element to count

    Returns:
        int: Count of occurrences
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

# Test
print("\n6. Count Occurrences:")
print(count_occurrences([[1, 2], [2, 3], [2, 4]], 2))  # Output: 3


# 7. Flatten a List of Lists of Lists (Deep Flatten)
def deep_flatten(lst):
    """
    Flattens a deeply nested list into a single list.

    Parameters:
        lst (list): Deeply nested list

    Returns:
        list: Flattened list
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

# Test
print("\n7. Deep Flatten:")
print(deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))  # Output: [1, 2, 3, 4, 5, 6, 7, 8]


# 8. Nested List Average
def average_nested(lst):
    """
    Calculates the average of all elements in a nested list.

    Parameters:
        lst (list): Nested list

    Returns:
        float: Average of all elements
    """
    def sum_and_count(lst):
        total = 0
        count = 0
        for item in lst:
            if isinstance(item, list):
                s, c = sum_and_count(item)
                total += s
                count += c
            else:
                total += item
                count += 1
        return total, count

    total, count = sum_and_count(lst)
    return total / count if count > 0 else 0

# Test
print("\n8. Nested List Average:")
print(average_nested([[1, 2], [3, 4], [5, 6]]))  # Output: 3.5

1. Flatten Nested List:
[1, 2, 3, 4, 5]

2. Access Nested Element:
6

3. Sum Nested List:
21

4. Remove Element:
[[1], [3], [4, 5]]

5. Find Maximum:
6

6. Count Occurrences:
3

7. Deep Flatten:
[1, 2, 3, 4, 5, 6, 7, 8]

8. Nested List Average:
3.5


10 To - Do - NumPy
Please complete all the problems listed below:
10.1 Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [5]:
import numpy as np

# Problem 1: Array Creation
print("=" * 50)
print("Problem 1: Array Creation")
print("=" * 50)

# 1. Initialize an empty array with size 2X2
empty_arr = np.empty((2, 2))
print("1. Empty array 2x2:")
print(empty_arr)

# 2. Initialize an all one array with size 4X2
ones_arr = np.ones((4, 2))
print("\n2. Ones array 4x2:")
print(ones_arr)

# 3. Return a new array of given shape and type, filled with fill value
filled_arr = np.full((3, 3), 7)
print("\n3. Array filled with 7 (3x3):")
print(filled_arr)

# 4. Return a new array of zeros with same shape and type as a given array
given_arr = np.array([[1, 2], [3, 4], [5, 6]])
zeros_like_arr = np.zeros_like(given_arr)
print("\n4. Zeros like given array:")
print(f"Original shape: {given_arr.shape}")
print(zeros_like_arr)

# 5. Return a new array of ones with same shape and type as a given array
ones_like_arr = np.ones_like(given_arr)
print("\n5. Ones like given array:")
print(ones_like_arr)

# 6. Convert list to numpy array
new_list = [1, 2, 3, 4]
numpy_arr = np.array(new_list)
print("\n6. Convert list to numpy array:")
print(f"List: {new_list}")
print(f"NumPy array: {numpy_arr}")

Problem 1: Array Creation
1. Empty array 2x2:
[[5.03085091e-315 0.00000000e+000]
 [2.14321575e-312 2.44029516e-312]]

2. Ones array 4x2:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Array filled with 7 (3x3):
[[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros like given array:
Original shape: (3, 2)
[[0 0]
 [0 0]
 [0 0]]

5. Ones like given array:
[[1 1]
 [1 1]
 [1 1]]

6. Convert list to numpy array:
List: [1, 2, 3, 4]
NumPy array: [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.


In [6]:
# Problem 2: Array Manipulation
print("\n" + "=" * 50)
print("Problem 2: Array Manipulation")
print("=" * 50)

# 1. Create an array with values ranging from 10 to 49
arr_10_49 = np.arange(10, 50)
print("1. Array from 10 to 49:")
print(arr_10_49)

# 2. Create a 3X3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 matrix with values 0-8:")
print(matrix_3x3)

# 3. Create a 3X3 identity matrix
identity_3x3 = np.eye(3)
print("\n3. 3x3 Identity matrix:")
print(identity_3x3)

# 4. Create a random array of size 30 and find the mean
random_arr = np.random.random(30)
mean_val = random_arr.mean()
print(f"\n4. Random array of size 30, mean = {mean_val:.6f}")

# 5. Create a 10X10 array with random values and find min and max
random_10x10 = np.random.random((10, 10))
min_val = random_10x10.min()
max_val = random_10x10.max()
print(f"\n5. 10x10 random array:")
print(f"   Minimum: {min_val:.6f}")
print(f"   Maximum: {max_val:.6f}")

# 6. Create a zero array of size 10 and replace 5th element with 1
zero_arr = np.zeros(10)
zero_arr[4] = 1  # 5th element (index 4)
print(f"\n6. Zero array with 5th element as 1:")
print(zero_arr)

# 7. Reverse an array
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print(f"\n7. Reverse array [1, 2, 0, 0, 4, 0]:")
print(reversed_arr)

# 8. Create a 2d array with 1 on border and 0 inside
border_arr = np.ones((5, 5))
border_arr[1:-1, 1:-1] = 0
print(f"\n8. 2D array with 1 on border, 0 inside:")
print(border_arr)

# 9. Create a 8X8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[::2, 1::2] = 1  # Even rows, odd columns
checkerboard[1::2, ::2] = 1  # Odd rows, even columns
print(f"\n9. 8x8 Checkerboard pattern:")
print(checkerboard)


Problem 2: Array Manipulation
1. Array from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix with values 0-8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array of size 30, mean = 0.537043

5. 10x10 random array:
   Minimum: 0.000347
   Maximum: 0.988270

6. Zero array with 5th element as 1:
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Reverse array [1, 2, 0, 0, 4, 0]:
[0 4 0 0 2 1]

8. 2D array with 1 on border, 0 inside:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

9. 8x8 Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]



Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [7]:
# Problem 3: Array Operations
print("\n" + "=" * 50)
print("Problem 3: Array Operations")
print("=" * 50)

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

print("Arrays:")
print(f"x = \n{x}")
print(f"y = \n{y}")
print(f"v = {v}")
print(f"w = {w}")

# 1. Add the two array
print("\n1. Add x and y:")
print(np.add(x, y))

# 2. Subtract the two array
print("\n2. Subtract y from x:")
print(np.subtract(x, y))

# 3. Multiply the array with any integers of your choice
print("\n3. Multiply x by 3:")
print(x * 3)

# 4. Find the square of each element of the array
print("\n4. Square of each element in x:")
print(np.square(x))

# 5. Find the dot product
print("\n5. Dot products:")
print(f"   v · w = {np.dot(v, w)}")
print(f"   x · v = {np.dot(x, v)}")
print(f"   x · y = \n{np.dot(x, y)}")

# 6. Concatenate x and y along row, v and w along column
concat_xy_row = np.concatenate((x, y), axis=0)  # or np.vstack
concat_vw_col = np.vstack((v, w)).T  # Stack vertically then transpose, or use column_stack
print("\n6. Concatenations:")
print(f"   x and y along row (axis=0):\n{concat_xy_row}")
print(f"   v and w along column:\n{np.column_stack((v, w))}")

# 7. Concatenate x and v - this will raise an error
print("\n7. Trying to concatenate x and v:")
try:
    concat_xv = np.concatenate((x, v))
    print(concat_xv)
except ValueError as e:
    print(f"   Error: {e}")
    print("   Explanation: x has shape (2,2) and v has shape (2,).")
    print("   They have different dimensions (2D vs 1D), so they cannot be concatenated directly.")
    print("   To fix this, we need to reshape v to (1,2) or (2,1):")
    v_reshaped = v.reshape(1, 2)
    print(f"   After reshaping v to {v_reshaped.shape}:")
    print(np.concatenate((x, v_reshaped), axis=0))


Problem 3: Array Operations
Arrays:
x = 
[[1 2]
 [3 5]]
y = 
[[5 6]
 [7 8]]
v = [ 9 10]
w = [11 12]

1. Add x and y:
[[ 6  8]
 [10 13]]

2. Subtract y from x:
[[-4 -4]
 [-4 -3]]

3. Multiply x by 3:
[[ 3  6]
 [ 9 15]]

4. Square of each element in x:
[[ 1  4]
 [ 9 25]]

5. Dot products:
   v · w = 219
   x · v = [29 77]
   x · y = 
[[19 22]
 [50 58]]

6. Concatenations:
   x and y along row (axis=0):
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
   v and w along column:
[[ 9 11]
 [10 12]]

7. Trying to concatenate x and v:
   Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
   Explanation: x has shape (2,2) and v has shape (2,).
   They have different dimensions (2D vs 1D), so they cannot be concatenated directly.
   To fix this, we need to reshape v to (1,2) or (2,1):
   After reshaping v to (1, 2):
[[ 1  2]
 [ 3  5]
 [ 9 10]]


  Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [8]:
# Problem 4: Matrix Operations
print("\n" + "=" * 50)
print("Problem 4: Matrix Operations")
print("=" * 50)

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

print(f"A = \n{A}")
print(f"B = \n{B}")

# 1. Prove A.A^-1 = I
A_inv = np.linalg.inv(A)
product = np.dot(A, A_inv)
print("\n1. Prove A · A^(-1) = I:")
print(f"   A^(-1) = \n{A_inv}")
print(f"   A · A^(-1) = \n{product}")
print(f"   Is it close to I? {np.allclose(product, np.eye(2))}")

# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n2. Prove AB ≠ BA:")
print(f"   AB = \n{AB}")
print(f"   BA = \n{BA}")
print(f"   Are they equal? {np.array_equal(AB, BA)}")

# 3. Prove (AB)^T = B^T · A^T
AB_T = AB.T
BT_AT = np.dot(B.T, A.T)
print("\n3. Prove (AB)^T = B^T · A^T:")
print(f"   (AB)^T = \n{AB_T}")
print(f"   B^T · A^T = \n{BT_AT}")
print(f"   Are they equal? {np.allclose(AB_T, BT_AT)}")

# Solve system of linear equations
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

print("\n" + "=" * 50)
print("Solving System of Linear Equations")
print("=" * 50)

# Coefficient matrix A
A_eq = np.array([[2, -3, 1],
                 [1, -1, 2],
                 [3, 1, -1]])
# Constants matrix B
B_eq = np.array([-1, -3, 9])

print(f"Coefficient matrix A:\n{A_eq}")
print(f"Constants B: {B_eq}")

# Method 1: Using inverse (A·X = B => X = A^(-1)·B)
A_inv_eq = np.linalg.inv(A_eq)
X_inv = np.dot(A_inv_eq, B_eq)
print(f"\nSolution using inverse method:")
print(f"x = {X_inv[0]:.4f}, y = {X_inv[1]:.4f}, z = {X_inv[2]:.4f}")

# Method 2: Using np.linalg.solve (recommended)
X_solve = np.linalg.solve(A_eq, B_eq)
print(f"\nSolution using np.linalg.solve:")
print(f"x = {X_solve[0]:.4f}, y = {X_solve[1]:.4f}, z = {X_solve[2]:.4f}")

# Verification
verification = np.dot(A_eq, X_solve)
print(f"\nVerification (A·X should equal B): {verification}")
print(f"Original B: {B_eq}")
print(f"Match: {np.allclose(verification, B_eq)}")


Problem 4: Matrix Operations
A = 
[[3 4]
 [7 8]]
B = 
[[5 3]
 [2 1]]

1. Prove A · A^(-1) = I:
   A^(-1) = 
[[-2.    1.  ]
 [ 1.75 -0.75]]
   A · A^(-1) = 
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
   Is it close to I? True

2. Prove AB ≠ BA:
   AB = 
[[23 13]
 [51 29]]
   BA = 
[[36 44]
 [13 16]]
   Are they equal? False

3. Prove (AB)^T = B^T · A^T:
   (AB)^T = 
[[23 51]
 [13 29]]
   B^T · A^T = 
[[23 51]
 [13 29]]
   Are they equal? True

Solving System of Linear Equations
Coefficient matrix A:
[[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]
Constants B: [-1 -3  9]

Solution using inverse method:
x = 2.0000, y = 1.0000, z = -2.0000

Solution using np.linalg.solve:
x = 2.0000, y = 1.0000, z = -2.0000

Verification (A·X should equal B): [-1. -3.  9.]
Original B: [-1 -3  9]
Match: True


10.2 Experiment: How Fast is Numpy?
In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:
1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.
2. Element-wise Multiplication
• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.
3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.
4. Matrix Multiplication

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [9]:
import time
import numpy as np

print("=" * 60)
print("10.2 Experiment: How Fast is NumPy?")
print("=" * 60)

size = 1_000_000
list_size = 1000  # For matrix multiplication

# Create data
python_list1 = list(range(size))
python_list2 = list(range(size))
numpy_arr1 = np.arange(size)
numpy_arr2 = np.arange(size)

# For matrix multiplication
python_matrix1 = [[i for i in range(list_size)] for _ in range(list_size)]
python_matrix2 = [[i for i in range(list_size)] for _ in range(list_size)]
numpy_matrix1 = np.arange(list_size * list_size).reshape(list_size, list_size)
numpy_matrix2 = np.arange(list_size * list_size).reshape(list_size, list_size)

print(f"\nArray/List size for element-wise ops: {size:,}")
print(f"Matrix size for multiplication: {list_size}x{list_size}")

# 1. Element-wise Addition
print("\n" + "-" * 60)
print("1. ELEMENT-WISE ADDITION")
print("-" * 60)

# Python Lists
start = time.time()
python_sum = [python_list1[i] + python_list2[i] for i in range(size)]
python_time = time.time() - start
print(f"Python Lists:     {python_time:.6f} seconds")

# NumPy Arrays
start = time.time()
numpy_sum = numpy_arr1 + numpy_arr2
numpy_time = time.time() - start
print(f"NumPy Arrays:     {numpy_time:.6f} seconds")
print(f"Speedup:          {python_time/numpy_time:.2f}x faster")

# 2. Element-wise Multiplication
print("\n" + "-" * 60)
print("2. ELEMENT-WISE MULTIPLICATION")
print("-" * 60)

# Python Lists
start = time.time()
python_mul = [python_list1[i] * python_list2[i] for i in range(size)]
python_time = time.time() - start
print(f"Python Lists:     {python_time:.6f} seconds")

# NumPy Arrays
start = time.time()
numpy_mul = numpy_arr1 * numpy_arr2
numpy_time = time.time() - start
print(f"NumPy Arrays:     {numpy_time:.6f} seconds")
print(f"Speedup:          {python_time/numpy_time:.2f}x faster")

# 3. Dot Product
print("\n" + "-" * 60)
print("3. DOT PRODUCT")
print("-" * 60)

# Python Lists
start = time.time()
python_dot = sum(python_list1[i] * python_list2[i] for i in range(size))
python_time = time.time() - start
print(f"Python Lists:     {python_time:.6f} seconds")

# NumPy Arrays
start = time.time()
numpy_dot = np.dot(numpy_arr1, numpy_arr2)
numpy_time = time.time() - start
print(f"NumPy Arrays:     {numpy_time:.6f} seconds")
print(f"Speedup:          {python_time/numpy_time:.2f}x faster")

# 4. Matrix Multiplication (using smaller size for Python)
print("\n" + "-" * 60)
print("4. MATRIX MULTIPLICATION (100x100 for Python, 1000x1000 for NumPy)")
print("-" * 60)

# Python Lists (100x100 to avoid too long wait)
small_size = 100
py_mat1 = [[i for i in range(small_size)] for _ in range(small_size)]
py_mat2 = [[i for i in range(small_size)] for _ in range(small_size)]

start = time.time()
python_result = [[sum(a * b for a, b in zip(row, col)) for col in zip(*py_mat2)] for row in py_mat1]
python_time = time.time() - start
print(f"Python Lists (100x100):     {python_time:.6f} seconds")

# NumPy Arrays (1000x1000)
start = time.time()
numpy_result = np.dot(numpy_matrix1, numpy_matrix2)
numpy_time = time.time() - start
print(f"NumPy Arrays (1000x1000):   {numpy_time:.6f} seconds")

# Compare same size for fair comparison
numpy_matrix_small1 = np.arange(small_size * small_size).reshape(small_size, small_size)
numpy_matrix_small2 = np.arange(small_size * small_size).reshape(small_size, small_size)

start = time.time()
numpy_small_result = np.dot(numpy_matrix_small1, numpy_matrix_small2)
numpy_small_time = time.time() - start
print(f"NumPy Arrays (100x100):     {numpy_small_time:.6f} seconds")
print(f"Speedup (same size):        {python_time/numpy_small_time:.2f}x faster")

print("\n" + "=" * 60)
print("CONCLUSION: NumPy is significantly faster due to:")
print("- Vectorized operations (no Python loops)")
print("- Optimized C/Fortran backend")
print("- Contiguous memory layout")
print("- SIMD instructions")
print("=" * 60)

10.2 Experiment: How Fast is NumPy?

Array/List size for element-wise ops: 1,000,000
Matrix size for multiplication: 1000x1000

------------------------------------------------------------
1. ELEMENT-WISE ADDITION
------------------------------------------------------------
Python Lists:     0.116724 seconds
NumPy Arrays:     0.004735 seconds
Speedup:          24.65x faster

------------------------------------------------------------
2. ELEMENT-WISE MULTIPLICATION
------------------------------------------------------------
Python Lists:     0.120558 seconds
NumPy Arrays:     0.004318 seconds
Speedup:          27.92x faster

------------------------------------------------------------
3. DOT PRODUCT
------------------------------------------------------------
Python Lists:     0.167675 seconds
NumPy Arrays:     0.002254 seconds
Speedup:          74.38x faster

------------------------------------------------------------
4. MATRIX MULTIPLICATION (100x100 for Python, 1000x1000 for NumPy